version: "3.7"
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    image: jupyter/datascience-notebook:latest
    #command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
    volumes:
      - ./:/home/jovyan/work
    ports:
      - 8888:${WEBSITES_PORT:-80}
      - 8000:8000
    environment:
      - JUPYTER_ENABLE_LAB: "yes"
    container_name: mercury-dashboard-bartl
