version: "3.7"
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    image: jupyter/datascience-notebook:latest
    #command: "start-notebook.sh --LabApp.token='' --LabApp.password=''"
    volumes:
      - ./:/home/jovyan/work
      - ./:/home/jovyan/mercury
    ports:
      - 80:${MERCURY:-8000}
      #- 8888:${JUPYTER_NOTEBOOK:-8888}
      - 80:${MERCURY_SERVER_PORT:-80}
      - 443:${SSL:-443}
    environment:
      #- JUPYTER_ENABLE_LAB: "yes"
      - MERCURY=${MERCURY:-8000}
      - MERCURY_SERVER_PORT=${MERCURY_SERVER_PORT:-80}
      #- JUPYTER_NOTEBOOK=${JUPYTER_NOTEBOOK:-8888}
      - SSL=${SSL:-443}
    container_name: mercury-dashboard-bartl
