version: "3.7"
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    image: jupyter/datascience-notebook:latest
    command: "start-notebook.sh --ServerProvider.token='' --ServerProvider.password=''"
    volumes:
      - ./:/home/jovyan/work
    ports:
      - 8888:${JUPYTER_NOTEBOOK:-8888}
      - 8000:${MERCURY:-8000}
      - 8001:${FASTAPI:-8001}
      - 80:${MERCURY_SERVER_PORT:-80}
      - 443:${SSL:-443}
    environment:
      - JUPYTER_ENABLE_LAB: "yes"
      - MERCURY_SERVER_PORT=${MERCURY_SERVER_PORT:-80}
      - JUPYTER_NOTEBOOK=${JUPYTER_NOTEBOOK:-8888}
      - MERCURY=${MERCURY:-8000}
      - FASTAPI=${FASTAPI:-8001}
      - SSL=${SSL:-443}
    container_name: mercury-dashboard-bartl
